language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

before_install:
  -openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in api_keys.json.enc -out api_keys.json -d

install:
  - pip install -r requirements.txt
  - pip install codecov

env:
  -CODECOV_TOKEN="9c1280d3-80a6-4aaa-9538-10ff0aa7099d"

before_script: cd tests

script:
  - python test_base.py
  - python test_utils.py
  - coverage run test_base.py

after_success:
  - codecov